Add a retry with backoff

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -35,9 +35,25 @@ function aws_version_ge() {
   [[ ${current[1]} -gt ${wanted[1]} ]] && return 0
   [[ ${current[2]} -ge ${wanted[2]} ]] && return 0
 
-  echo "$version isn't ge $1"
+  echo "$version isn't ge $1" >&2
 
   return 1
+}
+
+# Retries a command on failure.
+function retry() {
+  local -r -i max_attempts="$1"; shift
+  local -i attempt_num=1
+
+  until "$@" ; do
+    if (( attempt_num == max_attempts )) ; then
+      echo "Attempt $attempt_num failed and there are no more attempts left!" >&2
+      return 1
+    else
+      echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..." >&2
+      sleep $(( attempt_num++ ))
+    fi
+  done
 }
 
 if [[ -z "${AWS_DEFAULT_REGION:-}" ]] ; then
@@ -74,7 +90,9 @@ if [[ "${BUILDKITE_PLUGIN_ECR_LOGIN:-}" =~ ^(true|1)$ ]] ; then
   fi
 
   # shellcheck disable=SC2068
-  ecr_login=$(aws ecr get-login ${login_args[@]+"${login_args[@]}"}) || exit $?
+  ecr_login=$(retry "${BUILDKITE_PLUGIN_ECR_RETRY:-5}" aws ecr get-login ${login_args[@]+"${login_args[@]}"}) || exit $?
+
+  echo "$ecr_login"
 
   # despite all the horror above, if we have docker > 17.06 it still breaks...
   eval "$(sed 's/-e none//' <<< "$ecr_login")"
