Document retry and add more tests

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -42,15 +42,21 @@ function aws_version_ge() {
 
 # Retries a command on failure.
 function retry() {
-  local -r -i max_attempts="$1"; shift
+  local -r -i retries="$1"; shift
+  local -i max_attempts=$((retries + 1))
   local -i attempt_num=1
+  local exit_code
 
   until "$@" ; do
-    if (( attempt_num == max_attempts )) ; then
-      echo "Attempt $attempt_num failed and there are no more attempts left!" >&2
-      return 1
+    exit_code=$?
+    echo "$attempt_num == $retries" >&2
+    if [[ $retries -eq 0 ]] ; then
+      return $exit_code
+    elif (( attempt_num == max_attempts )) ; then
+      echo "Login failed after $attempt_num attempts" >&2
+      return $exit_code
     else
-      echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..." >&2
+      echo "Login failed on attempt ${attempt_num} of ${max_attempts}. Trying again in $attempt_num seconds..." >&2
       sleep $(( attempt_num++ ))
     fi
   done
@@ -90,7 +96,7 @@ if [[ "${BUILDKITE_PLUGIN_ECR_LOGIN:-}" =~ ^(true|1)$ ]] ; then
   fi
 
   # shellcheck disable=SC2068
-  ecr_login=$(retry "${BUILDKITE_PLUGIN_ECR_RETRY:-5}" aws ecr get-login ${login_args[@]+"${login_args[@]}"}) || exit $?
+  ecr_login=$(retry "${BUILDKITE_PLUGIN_ECR_RETRIES:-0}" aws ecr get-login ${login_args[@]+"${login_args[@]}"}) || exit $?
 
   echo "$ecr_login"
 
